### ISSUE TITLE
"mamba" is not available in the shell

### ISSUE THREAD

**Issue by fkollingiv** [Dartmouth-Data-Analytics-Core/DAC-RNAseq-pipeline#20]
When i attempt to run the pipeline using snakemake --use-conda, I receive the following error:

Building DAG of jobs...
CreateCondaEnvironmentException:
The 'mamba' command is not available in the shell /usr/bin/bash that will be used by Snakemake. You have to ensure that it is in your PATH, e.g., first activating the conda base environment with `conda activate base`.The mamba package manager (https://github.com/mamba-org/mamba) is a fast and robust conda replacement. It is the recommended way of using Snakemake's conda integration. It can be installed with `conda install -n base -c conda-forge mamba`. If you still prefer to use conda, you can enforce that by setting `--conda-frontend conda`.

This has always happened when I run this pipeline on Discovery, but it works fine when I use '--conda-frontend conda'. No other issues running the pipeline, but it does not run (at least for me) the way it is described in the README.

**Comment by tjs000** [comment]
Can you paste the output of these three commands? (Or send it to me, if it contains paths you don't want to make public)
```
which conda
which mamba
conda info
```

**Comment by owenwilkins** [comment]
which conda
which mamba
conda ***@***.*** > ~] $ which conda
/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/owen/sharedconda/miniconda/condabin/conda
***@***.*** > ~] $ which mamba
/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/owen/sharedconda/miniconda/condabin/mamba
***@***.*** > ~] $ conda info

     active environment : None
            shell level : 0
       user config file : /dartfs-hpc/rc/home/d/d41294d/.condarc
populated config files : /dartfs-hpc/rc/home/d/d41294d/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/owen/sharedconda/miniconda  (writable)
      conda av data dir : /dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/owen/sharedconda/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : /dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/owen/sharedconda/miniconda/pkgs
                          /dartfs-hpc/rc/home/d/d41294d/.conda/pkgs
       envs directories : /dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/owen/sharedconda/miniconda/envs
                          /dartfs-hpc/rc/home/d/d41294d/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.5 Linux/3.10.0-1160.59.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 353664:480987
             netrc file : None
           offline mode : False

From: Tim Sullivan ***@***.***>
Date: Friday, November 11, 2022 at 4:19 PM
To: Dartmouth-Data-Analytics-Core/DAC-RNAseq-pipeline ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [Dartmouth-Data-Analytics-Core/DAC-RNAseq-pipeline] "mamba" is not available in the shell (Issue #20)

Can you paste the output of these three commands? (Or send it to me, if it contains paths you don't want to make public)

which conda

which mamba

conda info
