### ISSUE TITLE
Functionality updates

### ISSUE THREAD

**Issue by owenwilkins** [Dartmouth-Data-Analytics-Core/DAC-RNAseq-pipeline#27]
- add analysis module that flags possible genomic DNA contamination and high intron/intergenic mapping rates 
- In the UMI-based pipeline, CollectRNAseqMetrics & Markduplicates currently use the non deduped BAM file. It may make sense for these rules to use the deduped BAM file.

**Comment by tjs000** [comment]
I separated these feature requests into issues #28 and #29.  Closing this issue.
